### ISSUE TITLE
Project identifier or folder identifier in the timelogs

### ISSUE THREAD

**Issue by MarkBQE** [staviloglu/Taviloglu.Wrike.ApiClient#27]
####Quick Question

Hawala. Amazing library. Quick question how do I get the projects/folder(ids) in the time log get method response. Do I need to query a task for a time log and then get the parent of the task? I am filtering the time logs by a date range, passing the resource, project in the request parameters is not an option.

**Comment by staviloglu** [comment]
Hi @MarkBQE.

I'm happy that this library helped you.

Sorry for the late response 😞 I wonder if you have a solution for the requirement you got there, because this is just a wrapper around the Wrike API v4. 

If you can find a way checking the [documentation](https://developers.wrike.com/api/v4/timelogs/) then you should be able to do it using the library, if can't then we should talk 😅

**Comment by MarkBQE** [comment]
Merhaba. I did not end up using the library instead used the WRIKE APIs directly. My project is completed and delivered to the client, thanks for offering help though. teşekkür ederim

**Comment by staviloglu** [comment]
@MarkBQE Merhaba :) 
Thanks for the reply.
